### ISSUE TITLE
Images - use CDN instead of repo

### ISSUE THREAD

**Issue by goldylucks** [ASJvine/vod-platform#17]
Benefits:
- images served faster
- less burden on our server
- MUCH less burden on repo (for coders)
- can upload and use images without touching code (for admins and coders)

[cloudinary](http://cloudinary.com/) is working rather well for me for image hosting. The interface is super simple and intuitive. They also have video hosting which I haven't tried yet. It has a free option which will probably suffice for the first month of the business.

**Comment by ASJvine** [comment]
OK, great.

**Comment by goldylucks** [comment]
ok so you guys need to open an account there, and upload the images

**Comment by ASJvine** [comment]
The account has been created, and we're currently uploading the images and the videos.
