### ISSUE TITLE
add repo to travis ci

### ISSUE THREAD

**Issue by goldylucks** [ASJvine/vod-platform#18]
It's very simple, let me know if you need help.

**Comment by ASJvine** [comment]
OK, I'll do.

**Comment by ASJvine** [comment]
It's easy to setup, but could you send me the .travis.yml that I should use, because I've 0 experience on that.

**Comment by goldylucks** [comment]
I'll add the `.travis.yml` file. you need to add the repo the travis first, follow the [two first steps here](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A).

**Comment by ASJvine** [comment]
YEs, I've done that already, however it pops an issue due to the absence of the `.travis.yml
![screen shot 2017-03-28 at 21 02 42](https://cloud.githubusercontent.com/assets/15228714/24422524/21ed9a46-13fa-11e7-91e6-3a9be2ee05fc.png)
` file

**Comment by goldylucks** [comment]
indeed, I'll add a file later

**Comment by goldylucks** [comment]
added the file in #24
