### ISSUE TITLE
setup an heroku production app

### ISSUE THREAD

**Issue by goldylucks** [ASJvine/vod-platform#19]
I can't recommend [Herku](http://heroku.com/) enough.  
Deploying is super simple, it plays very nicely with [travis](https://travis-ci.org/), and scaling is a breeze.

**Comment by ASJvine** [comment]
Is it better Heroku than the normal AWS? Or AWS requires

**Comment by goldylucks** [comment]
You tell me.
Deploying to heroku takes 5 minutes ;)

they have a free plan, and 7$ / mo starter plan.

**Comment by ASJvine** [comment]
OK! Great!

**Comment by goldylucks** [comment]
add this addon to the heroku app:
mLab MongoDB :: Mongodb

This provides mongoDB support right out of the box :)

Also write here the app url so we can set it in the app constants

**Comment by ASJvine** [comment]
Ok, for the addon, but this means that I need to signup for mLab or is it a turnaround to use MongoDB directly? 

What do you mean by _**"Also write here the app url so we can set it in the app constants"**_?

**Comment by goldylucks** [comment]
you might need to signup quickly for mLab.

write here the url of the heroku app, it's our production app, where we will direct users and make api calls. it's something like my-app.herokuapp.com

**Comment by ASJvine** [comment]
OK, I do not have a custom domain yet, we've to buy one (need to choose the right name).
I add the mLab addon, currently we're using the sandbox, so it is a development one. Once we're ready to ship to production, I'll signup and get a real account.

![screen shot 2017-03-28 at 21 56 51](https://cloud.githubusercontent.com/assets/15228714/24424714/eb1a9dae-1401-11e7-92e2-ea94af1a3e1c.png)

**Comment by goldylucks** [comment]
sandbox is fine. no need to pay money for now.
What's the heroku app url?

**Comment by goldylucks** [comment]
@ASJvine I need the url for the production app and the staging app

**Comment by ASJvine** [comment]
@goldylucks I just did the domain transfer, I need to change the target and I'll send you both url. I'm waiting the namecheap answer.

**Comment by goldylucks** [comment]
@ASJvine update?

**Comment by ASJvine** [comment]
@goldylucks I've sent you a mail with the details (subject: Setup an heroku production app)

**Comment by goldylucks** [comment]
got it!
can u change the name to something meaningful, i.e. `keychn` ?
