### ISSUE TITLE
Integrate stripe

### ISSUE THREAD

**Issue by goldylucks** [ASJvine/vod-platform#22]
- [x] #36 - add SSL to production app
- [x] define subscription plans price points
- [x] create company stripe account and plans

**Comment by ASJvine** [comment]
is it solved?

**Comment by ASJvine** [comment]
@goldylucks , to facilitate the implementation, stripe already have a subscription feature. Are planning to implement such feature? [check it](https://stripe.com/subscriptions).

**Comment by goldylucks** [comment]
[ ] #36 - add SSL to production app
[ ] define subscription plans price points
[ ] create company stripe account and plans

**Comment by goldylucks** [comment]
@ASJvine 
check updated description

**Comment by ASJvine** [comment]
@goldylucks I've sent you a mail with the stripe details. (subject: Keychn Stripe)

**Comment by ASJvine** [comment]
@goldylucks I've sent you a mail with the details (subject: Setup an heroku production app)

**Comment by goldylucks** [comment]
@ASJvine see points 2 & 3 in the description. are they implemented?

**Comment by ASJvine** [comment]
@goldylucks all 3 points are implemented. 1st point is automatically implemented by heroku hobby package.
