### ISSUE TITLE
fix bootstrap css

### ISSUE THREAD

**Issue by goldylucks** [ASJvine/vod-platform#26]
right now we have a mixture of bootstrap and our own grid.
@ASJvine you want to remove bootstrap complete correct?

**Comment by ASJvine** [comment]
Correct, bootstrap should not be used for styling. We have already our own grid, and it would be nice to change the styling to use sass and flexbox to simplify the current code and make it more maintainable.

**Comment by goldylucks** [comment]
ok I will work on that

**Comment by ASJvine** [comment]
You can use a similar approach to this [repo (podcasts)](https://github.com/ASJvine/podcasts-itunes) if you consider that it is a good Sass approach or include the sass files in the same component's folder.

**Comment by goldylucks** [comment]
done in #24
