### ISSUE TITLE
implement facebook auth

### ISSUE THREAD

**Issue by goldylucks** [ASJvine/vod-platform#29]
@ASJvine you need to create 3 facebook apps for that, for staging, dev, and production
if I will do it then I'll have ownership on the apps.

1. Open [facebook dev account](https://developers.facebook.com/apps) if you don't already have one.
2. create 3 apps: VOD, VOD (dev), VOD (staging)
3. add me as the developer
4. notify me and I'll start working on this

**Comment by ASJvine** [comment]
@goldylucks , to add you as a developer, I need your fbid or [username](https://www.facebook.com/help/211813265517027).

**Comment by goldylucks** [comment]
facebook.com/adamgoldman47

**Comment by ASJvine** [comment]
@goldylucks, today Facebook let me add you as a developer. You can start working on that!
