### ISSUE TITLE
Optimise images

### ISSUE THREAD

**Issue by goldylucks** [ASJvine/vod-platform#31]
The images now weight a few MBs each and have super high resolution. We need to figure out the highest resolution needed for display (max size of their containers) and optimse based on that.

@ASJvine I need the exact dimensions from you.

**Comment by ASJvine** [comment]
@goldylucks I'm waiting the answer from the content creator in order to check the required resolution and dimensions. He's already optimising the images using Photoshop, but if you think that they're TOO big, we'll find a solution by reducing the resolution AND/OR the size.

**Comment by goldylucks** [comment]
what do u mean by "required resolution"?
We only need resolution as high as the pic dimensions we display on the site, like I said:

> We need to figure out the highest resolution needed for display (max size of their containers) and optimse based on that.

**Comment by ASJvine** [comment]
OK, I'm waiting the designer response.

**Comment by ASJvine** [comment]
@goldylucks I've sent you a mail with the details required and updated the images in cloudinary.
