### ISSUE TITLE
Add SSL to production app

### ISSUE THREAD

**Issue by goldylucks** [ASJvine/vod-platform#36]
**STATUS**: blocked by #44

According to [heroku](https://devcenter.heroku.com/articles/ssl), we get this for free when we get a paid Dyno, which we should get anyway for the production app

**Comment by goldylucks** [comment]
@ASJvine this needs to be solved on your end

**Comment by ASJvine** [comment]
@goldylucks I've sent you a mail with the details (subject: Setup an heroku production app). Apparently is already set.

**Comment by ASJvine** [comment]
@goldylucks there's an issue of the deployment. I've sent you a message via Facebook.

**Comment by goldylucks** [comment]
looks like it's working now
