### ISSUE TITLE
View: My Recipes

### ISSUE THREAD

**Issue by goldylucks** [ASJvine/vod-platform#38]
- [x] get mocks - @ASJvine 
- [x] answer questions - @ASJvine 
- [ ] implement view - @goldylucks

#### client
- [x] add react route
- [x] add page
- [x] add component
- [x] connect user menu to route
- [x] add endpoint
- [x] add redux actions
- [x] add reducer processing

#### server
- [x] add test case
- [x] add controller method
- [x] add endpoint

**Comment by ASJvine** [comment]
@goldylucks I've sent a mail with the mocks from keychn mail.

**Comment by goldylucks** [comment]
@ASJvine 
My recipes are recipes the user has bought individually?
or recipes he started working on?

if it's the latter, how's the user actually "starting" it?

**Comment by ASJvine** [comment]
@goldylucks My recipes are the recipes "bought" individually (using the Keychn App) that are set by the admin.
