### ISSUE TITLE
Connect CI to heroku deploy

### ISSUE THREAD

**Issue by goldylucks** [ASJvine/vod-platform#42]
- [x] add relevant code `.travis.yml` @goldylucks
- [x] send @goldylucks travis encrypted heroku api keys to `.travis.yml` @ASJvine 
- [x] add travis encrypted heroku api keys to `.travis.yml` @goldylucks

**Comment by goldylucks** [comment]
@ASJvine 
- [ ] get your heroku API KEY [here](https://dashboard.heroku.com/account)
- [ ] encrypt it using `$ travis encrypt API_KEY_HERE` ([further reading](https://docs.travis-ci.com/user/encryption-keys/))
- [ ] send me the output

**Comment by ASJvine** [comment]
@goldylucks I've sent you via mail the encrypted Heroku API KEY.

**Comment by goldylucks** [comment]
I'm getting 401 error from travis, `bad credentials`.

what command did u use to encrypt your key?
what exact steps did u take?

**Comment by ASJvine** [comment]
1st step Heroku API KEY copy
2nd step install the gem install travis
3rd step cd to the project (I just clone the repo to a new folder)
4rth step travis encrypt SOMEVAR="secretvalue"

**Comment by goldylucks** [comment]
I think the problem is here:
`$ travis encrypt SOMEVAR="secretvalue"`

Try what I've written exactly like in the description above:
`$ travis encrypt API_KEY_HERE`

notice there's no SOMEVAR nor equal sign and no quotation marks

**Comment by ASJvine** [comment]
@goldylucks check your mail. Sent!

**Comment by goldylucks** [comment]
got it, works
