### ISSUE TITLE
point DNS to heroku app

### ISSUE THREAD

**Issue by goldylucks** [ASJvine/vod-platform#44]
I've ran `keychn.com` through [whois](https://www.whois.net/):    
Name Server: DNS1.REGISTRAR-SERVERS.COM  
Name Server: DNS2.REGISTRAR-SERVERS.COM  

it should probably be one of these two:
`keychn.com.herokudns.com`
`www.keychn.com.herokudns.com`
@ASJvine check it with your registrar

**Comment by goldylucks** [comment]
DNS still pointing at the same location.
U have to change it in your domain registrar, not in heroku.

**Comment by ASJvine** [comment]
I've changed it in NameCheap, but the change is not set yet. Check the picture in Facebook.

**Comment by ASJvine** [comment]
@goldylucks it seems that part of the problem has been solved. Try to connect to [http://www.keychn.com/](url)

Please check the errors given by Heroku
<img width="696" alt="screen shot 2017-06-01 at 23 25 30" src="https://cloud.githubusercontent.com/assets/15228714/26701490/a2bd7650-4721-11e7-8c9e-75284bc75b53.png">

**Comment by goldylucks** [comment]
Looks like this is done, indeed
